### ISSUE TITLE
Unable to import SatNOGS satellites

### ISSUE THREAD

**Issue by janvgils** [tomvdb/satellite-server#2]
The option to add a SatNOGS satellite isn't working.
Looking at the browser developer tools we get the following error:

```
Access to XMLHttpRequest at 'https://db.satnogs.org/api/tle/?format=json&norad_cat_id=32789' from origin 'http://x.x.x.x:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
jquery-3.6.0.min.js:2 GET https://db.satnogs.org/api/tle/?format=json&norad_cat_id=32789 net::ERR_FAILED 200 send @ jquery-3.6.0.min.js:2 ajax @ jquery-3.6.0.min.js:2 retrieveData @ add_satellite:308 onclick @ add_satellite:256
```

**Comment by tomvdb** [comment]
This is due a security feature in your browser. Turns out I had it switched off on my development pc during testing. I've added a quick test in which should resolve it now. If you can try it out and confirm then I'll refine it a bit more.

You should be able to just to a 

`git pull`

your config and database shouldn't be overwritten

**Comment by janvgils** [comment]
Thanks for the update, this solved the SatNOGS import function.

**Comment by tomvdb** [comment]
Thanks for reporting the issue :)

Feature requests and bug reports always welcome :)
